install bash
install binutils
install brew-cask
install cmake
install coreutils
install ctags
install ddrescue
install findutils
install git
install grep
install lua
install lzip
install make
install openssh
install openssl
install p7zip
install python
install qemu
install readline
install reattach-to-user-namespace
install rename
install sqlite
install tmux
install trash
install w3m
install wakeonlan
install wget
install youtube-dl
install zsh

cask appcleaner
cask bettertouchtool
cask coconutbattery
cask day-o
cask disconnect
cask disk-inventory-x
cask evernote
cask flash
cask flash-player
cask flashlight
cask flux
cask geektool
cask gimp
cask google-chrome
cask google-hangouts
cask iterm2
cask karabiner
cask keepingyouawake
cask lastpass
cask macvim
cask openzfs
cask osxfuse
cask seil
cask sopcast
cask steam
cask telegram
cask the-unarchiver
cask tigervnc-viewer
cask today-scripts
cask utorrent
cask xquartz
cask xtrafinder
